<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Comercio Electrónico</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; }
        nav { background: #333; color: white; padding: 10px; text-align: center; }
        nav button { margin: 5px; padding: 10px; background: #555; color: white; border: none; cursor: pointer; }
        nav button:hover { background: #777; }
        #content { padding: 20px; }
        .hidden { display: none; }
        .articulo { border: 1px solid #ccc; padding: 10px; margin: 10px 0; display: flex; align-items: center; }
        .articulo img { width: 100px; height: 100px; margin-right: 10px; }
    </style>
</head>
<body>
    <nav>
        <button data-page="captura">Captura de artículo</button>
        <button data-page="compra">Compra de artículos</button>
        <button data-page="carrito">Carrito de compra</button>
    </nav>
    <div id="content">
        <div id="captura" class="hidden">
            <h2>Captura de Artículo</h2>
            <input id="nombre" placeholder="Nombre" type="text">
            <textarea id="descripcion" placeholder="Descripción"></textarea>
            <input id="precio" placeholder="Precio" type="number" min="0" step="0.01">
            <input id="cantidad" placeholder="Cantidad" type="number" min="1">
            <input id="foto" type="file" accept="image/*">
            <button data-action="capturarArticulo">Guardar</button>
        </div>
        <div id="compra" class="hidden">
            <h2>Compra de Artículos</h2>
            <input id="keyword" placeholder="Buscar artículos" type="text">
            <button data-action="buscarArticulos">Buscar</button>
            <div id="resultados"></div>
        </div>
        <div id="carrito" class="hidden">
            <h2>Carrito de Compra</h2>
            <div id="lista-carrito"></div>
            <button data-action="vaciarCarrito">Vaciar carrito</button>
            <button data-action="seguirComprando">Seguir comprando</button>
        </div>
    </div>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const articulos = [];
            const carrito = [];

            function showPage(page) {
                document.querySelectorAll("#content > div").forEach(div => div.classList.add("hidden"));
                document.getElementById(page).classList.remove("hidden");
            }

            function capturarArticulo() {
                const nombre = document.getElementById("nombre").value;
                const descripcion = document.getElementById("descripcion").value;
                const precio = parseFloat(document.getElementById("precio").value);
                const cantidad = parseInt(document.getElementById("cantidad").value);
                const fotoInput = document.getElementById("foto").files[0];

                if (!nombre || !descripcion || isNaN(precio) || isNaN(cantidad) || !fotoInput) {
                    alert("Por favor, llena todos los campos correctamente.");
                    return;
                }

                const reader = new FileReader();
                reader.onload = () => {
                    const nuevoArticulo = {
                        id: articulos.length + 1,
                        nombre,
                        descripcion,
                        precio,
                        cantidad,
                        fotografia: reader.result
                    };
                    articulos.push(nuevoArticulo);
                    alert("Artículo capturado correctamente.");
                    limpiarFormularioCaptura();
                };
                reader.readAsDataURL(fotoInput);
            }

            function limpiarFormularioCaptura() {
                document.getElementById("nombre").value = "";
                document.getElementById("descripcion").value = "";
                document.getElementById("precio").value = "";
                document.getElementById("cantidad").value = "";
                document.getElementById("foto").value = "";
            }

            function buscarArticulos() {
                const keyword = document.getElementById("keyword").value.toLowerCase();
                const resultados = document.getElementById("resultados");

                const articulosFiltrados = articulos.filter(art => 
                    art.nombre.toLowerCase().includes(keyword) || 
                    art.descripcion.toLowerCase().includes(keyword)
                );

                resultados.innerHTML = articulosFiltrados.length 
                    ? articulosFiltrados.map(art => `
                        <div class="articulo">
                            <img src="${art.fotografia}" alt="${art.nombre}">
                            <div>
                                <h3>${art.nombre}</h3>
                                <p>${art.descripcion}</p>
                                <p>Precio: $${art.precio.toFixed(2)}</p>
                                <p>Stock: ${art.cantidad}</p>
                                <input type="number" min="1" max="${art.cantidad}" value="1" id="cantidad-${art.id}">
                                <button data-id="${art.id}">Agregar al carrito</button>
                            </div>
                        </div>
                    `).join("")
                    : "<p>No se encontraron resultados.</p>";

                document.querySelectorAll("#resultados button").forEach(button => {
                    button.addEventListener("click", () => {
                        const idArticulo = parseInt(button.getAttribute("data-id"));
                        const cantidad = parseInt(document.getElementById(`cantidad-${idArticulo}`).value);
                        agregarCarrito(idArticulo, cantidad);
                    });
                });
            }

            function agregarCarrito(idArticulo, cantidad) {
                const articulo = articulos.find(a => a.id === idArticulo);

                if (!articulo || cantidad > articulo.cantidad) {
                    alert("Cantidad no disponible.");
                    return;
                }

                articulo.cantidad -= cantidad;

                const articuloEnCarrito = carrito.find(a => a.id === idArticulo);
                if (articuloEnCarrito) {
                    articuloEnCarrito.cantidad += cantidad;
                } else {
                    carrito.push({ ...articulo, cantidad });
                }

                alert("Artículo agregado al carrito.");
                buscarArticulos(); // Actualizar lista de resultados
            }

            function mostrarCarrito() {
                const listaCarrito = document.getElementById("lista-carrito");
                listaCarrito.innerHTML = carrito.length
                    ? carrito.map(art => `
                        <div>
                            <h3>${art.nombre}</h3>
                            <p>${art.descripcion}</p>
                            <p>Precio: $${art.precio.toFixed(2)}</p>
                            <p>Cantidad: ${art.cantidad}</p>
                        </div>
                    `).join("")
                    : "<p>El carrito está vacío.</p>";
            }

            function vaciarCarrito() {
                carrito.forEach(item => {
                    const articulo = articulos.find(a => a.id === item.id);
                    articulo.cantidad += item.cantidad;
                });
                carrito.splice(0, carrito.length);
                alert("Carrito vaciado.");
                mostrarCarrito();
            }

            document.querySelector("nav").addEventListener("click", (e) => {
                if (e.target.tagName === "BUTTON") {
                    showPage(e.target.getAttribute("data-page"));
                }
            });

            document.getElementById("content").addEventListener("click", (e) => {
                if (e.target.tagName === "BUTTON") {
                    const action = e.target.getAttribute("data-action");
                    if (action === "capturarArticulo") capturarArticulo();
                    if (action === "buscarArticulos") buscarArticulos();
                    if (action === "vaciarCarrito") vaciarCarrito();
                    if (action === "seguirComprando") showPage("compra");
                }
            });

            showPage("captura");
        });
    </script>
</body>
</html>
